name: tests-and-linter-check

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests-and-linter-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run lint task
        run: make lint

      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Acemore_fizz-buzz
            -Dsonar.organization=acemore
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**
